### ISSUE TITLE
NPE with animator

### ISSUE THREAD

**Issue by randombyte-developer** [SimonFlash/TeslaPowered#11]
Creating an Animator and starting it doesn't require setting a completion callback. So when we get [here](https://github.com/SimonFlash/TeslaPowered/blob/d1838cac05e738766d903095615bf7edbd939f0e/TeslaLibs/src/main/java/com/mcsimonflash/sponge/teslalibs/animation/Animator.java#L71) a NPE is thrown if the callback wasn't set.

I suggestion either enforcing a callback, respecting the nullability or setting a default "empty" callback.

And since we are here: Maybe make `onCompletion(...)` return the Animator itself for a builder style pattern?

**Comment by SimonFlash** [comment]
I intended to close this with v1.1.4 commit, but this has indeed been addressed with a simple null check.

Most of the Animation library is outdated, incomplete, and doesn't match the current style of the project (such as the `onCompletion` method as you said). I've opted to deprecate them for the meantime until the library can be refactored.
