### ISSUE TITLE
Layout builder improvement

### ISSUE THREAD

**Issue by randombyte-developer** [SimonFlash/TeslaPowered#14]
Small suggestion in https://github.com/SimonFlash/TeslaPowered/blob/1f4e78b7c527cd3c4e6665e0218f28de313b5f02/TeslaLibs/src/main/java/com/mcsimonflash/sponge/teslalibs/inventory/Layout.java#L95:

Make it to `set(Element, int, int...)` to prevent accidentally writing `set(myElement)` (which happens sometimes).

**Comment by SimonFlash** [comment]
I've done this myself a couple times, so I understand the frustration. However, this couldn't be fixed until the next major release (binary breakage to remove the existing method), and I personally believe this to be bad practice. It may be feasible to add a fail-fast check at some point, but technically that's also a breaking change.
