### ISSUE TITLE
Inventory API: Allow modifications affecting the player inventory

### ISSUE THREAD

**Issue by randombyte-developer** [SimonFlash/TeslaPowered#15]
Simons words: `I'll probably have to have some type of action consumer for what happens when an action is outside the gui.`

My goal is to implement some sort of trade / backpack GUI which allows players to move stuff from their inventory to the Tesla `View`. Currently TeslaPowered cancels all events by default, this can be prevented by un-cancelling the event in an `Action` of an `Element`. Since the click action happens outside of the GUI, no `Element`(and its action callback) can be added to handle that type of situation.

**Comment by SimonFlash** [comment]
This is a difficult situation. My expectation when I attach a listener to a custom inventory is that I'm only listening to events fired by the inventory I've created, which is certainly not the player's inventory. I'll have to do some reasearch on this and see what exactly is happening here to understand the best way to fix it.

**Comment by randombyte-developer** [comment]
I can think of two things:

1. Have some global listener for all inventory events (I don't like that particularly well)
2. Make TeslaLibs not canceling all incoming inventory events. Maybe provide a simple function `allowModifications(boolean)` or `blockModifications(boolean)`, which includes the player inventory. I understand that the current `View` doesn't have anything to do with the player inventory, but I can't think of anything better.

**Comment by SimonFlash** [comment]
I agree that the first isn't really an option - I've been careful to avoid anything that spans a global state as much as possible to avoid compatibility issues among plugins.

> I understand that the current View doesn't have anything to do with the player inventory

I wholeheartedly agree with statement. Within the context of TeslaLibs, I would say that the `View` only encompases the main inventory (in other words, *not* the player's inventory). As such, I consider this to be uninteded behavior - we should only be handling events that interact directly with the inventory declared by the `View`. This is a fair abstraction that comes with the library.

Ultimately, my short term resolution is to ensure that the View only handles events in the enclosing inventory - anything outside of that (like in the player's inventory) is not something we should restrict. From there, we can look into features like blocking outside modifications or even attaching listeners to the player inventory at a later date.

**Comment by randombyte-developer** [comment]
> Ultimately, my short term resolution is to ensure that the View only handles events in the enclosing inventory - anything outside of that (like in the player's inventory) is not something we should restrict.

I like that and definitely don't think it would only be a short term solution. I *guess* that this is just checking if the Slot the action occurred in is a child of the `View`'s underlying inventory.
